name: utec-bigdata-2022-1
channels:
  - defaults
dependencies:
  - python=3.7 # Google Colab is still on Python 3.6
  - cudatoolkit=10.1
  - cudnn=7.6
  - mongodb
  - mongo-tools
  - redis
  - pip
  - pip:
      - pip-tools
